<a href="https://colab.research.google.com/github/AayushiPatel123/Machine-Learning/blob/Feature-Selection/Feature_Selection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
cancer_dataset=pd.read_csv('Breastcancer.csv')

# MrMr Feature Selection Method

In [ ]:
!pip install mrmr_selection

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 72 kB 685 kB/s 
  Created wheel for sklearn: filename=sklearn-0.0.post1-py3-none-any.whl size=2344 sha256=5ea3481e9fcb8b5cacf896943023deea78b3ca05281c8df9316aa9987f4ec2c2
  Stored in directory: /root/.cache/pip/wheels/42/56/cc/4a8bf86613aafd5b7f1b310477667c1fca5c51c3ae4124a003
Successfully built sklearn


In [ ]:

X_cancer = cancer_dataset.iloc[:,:-1]#independent variable columns
Y_cancer = cancer_dataset.iloc[:,-1] #dependent variable
from mrmr import mrmr_classif
X_features = mrmr_classif(X=X_cancer, y=Y_cancer, K=20)

100%|██████████| 20/20 [01:28<00:00,  4.42s/it]


In [ ]:
X_cancer = cancer_dataset[["FOXA1","HES4","IDH2","ZAK","ATL2","CORO2B","AGR3","AR","TBC1D9","SLC7A8",
                           "ZFP36L1","GATA3","TFF3","MIEN1","CENPF","XBP1","UGT8","AGR2","TESC","THSD4" ]]
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split( X_cancer, Y_cancer, test_size=0.2,random_state=0)

## SVM Linear Classification Method

In [ ]:
from sklearn.svm import SVC

#Linear Classifier
cancer_linear_classifier = SVC(C=1.0,kernel='linear')
cancer_linear_classifier.fit(X_train,y_train)
Y_cancer_linear_pred = cancer_linear_classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score
cancer_linear_cm = confusion_matrix(y_test,Y_cancer_linear_pred)
print("cm of linear svm is \n ", cancer_linear_cm)

circles_linear_ac = (accuracy_score(y_test,Y_cancer_linear_pred)*100)
print("accuracy of linear svm is \n ", circles_linear_ac)

cm of linear svm is 
  [[7 0 0 0]
 [0 7 1 0]
 [0 0 9 0]
 [0 0 4 4]]
accuracy of linear svm is 
  84.375


## Random Forest Classification Method

In [ ]:
from sklearn.ensemble import RandomForestClassifier
cancer_RF_classifier = RandomForestClassifier( random_state=0, criterion = 'entropy', n_estimators = 150)
cancer_RF_classifier.fit(X_train,y_train)
Y_cancer_RF_pred = cancer_RF_classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score
cancer_RF_cm = confusion_matrix(y_test,Y_cancer_RF_pred)
print("cm of Random Forest is \n ", cancer_RF_cm)

circles_RF_ac = (accuracy_score(y_test,Y_cancer_RF_pred)*100)
print("accuracy of Random Forest  is \n ", circles_RF_ac)

cm of Random Forest is 
  [[7 0 0 0]
 [0 8 0 0]
 [0 0 9 0]
 [0 0 5 3]]
accuracy of Random Forest  is 
  84.375


## Neural networks

In [ ]:
Y_cancer = cancer_dataset.iloc[:,-1] #dependent variable
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
Y_cancer = labelencoder.fit_transform(Y_cancer)
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split( X_cancer, Y_cancer, test_size=0.2,random_state=0)
import tensorflow as tf
from tensorflow import keras
model_2 = tf.keras.models.Sequential()
#Input and hidden sigmoid
model_2.add(tf.keras.layers.Dense(units = 6, activation = 'sigmoid'))
#2nd Hidden layer
model_2.add(tf.keras.layers.Dense(units = 7, activation = 'sigmoid'))
#output layer
model_2.add(tf.keras.layers.Dense(units = 5, activation = 'relu'))
#compiling the NN
model_2.compile ( optimizer='sgd', metrics= ['accuracy'] ,loss= 'binary_crossentropy' )
# fitting the model with batch learning
model_2.fit(X_train,y_train, batch_size = 32, epochs = 50,validation_data=(X_cancer, Y_cancer) )

Epoch 1/50
4/4 [==============================] - 1s 80ms/step - loss: 6.0968 - accuracy: 0.1111 - val_loss: 5.4710 - val_accuracy: 0.0823
Epoch 2/50
4/4 [==============================] - 0s 10ms/step - loss: 4.2887 - accuracy: 0.1032 - val_loss: 2.9836 - val_accuracy: 0.0823
Epoch 3/50
4/4 [==============================] - 0s 12ms/step - loss: 2.9009 - accuracy: 0.1032 - val_loss: 2.4983 - val_accuracy: 0.0823
Epoch 4/50
4/4 [==============================] - 0s 11ms/step - loss: 1.4681 - accuracy: 0.1190 - val_loss: -0.5770 - val_accuracy: 0.2468
Epoch 5/50
4/4 [==============================] - 0s 10ms/step - loss: -2.2603 - accuracy: 0.2540 - val_loss: -3.7377 - val_accuracy: 0.2468
Epoch 6/50
4/4 [==============================] - 0s 15ms/step - loss: -4.2199 - accuracy: 0.2540 - val_loss: -3.2267 - val_accuracy: 0.2468
Epoch 7/50
4/4 [==============================] - 0s 11ms/step - loss: -4.0498 - accuracy: 0.2540 - val_loss: -3.9260 - val_accuracy: 0.2468
Epoch 8/50
4/4 [====

In [ ]:
from sklearn.neural_network import MLPClassifier
circles_NN_classifier = MLPClassifier(solver = 'lbfgs', activation = 'logistic')
circles_NN_classifier.fit(X_train,y_train)
Y_circles_NN_pred = circles_NN_classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score
circles_NN_cm = confusion_matrix(y_test,Y_circles_NN_pred)
print ("Confusion matrix for circles Dataset with MLP classifier is : ")
print(circles_NN_cm)

circles_NN_ac = (accuracy_score(y_test,Y_circles_NN_pred)*100)
print ("Accuracy for circles Dataset with MLP classifier is :")
print(circles_NN_ac)

Confusion matrix for circles Dataset with MLP classifier is : 
[[7 0 0 0]
 [0 8 0 0]
 [0 0 9 0]
 [0 0 3 5]]
Accuracy for circles Dataset with MLP classifier is :
90.625


# Information Gain Feature Selection Method

In [ ]:
X_cancer = cancer_dataset.iloc[:,:-1]#independent variable columns
Y_cancer = cancer_dataset.iloc[:,-1] #dependent variable
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
Y_cancer = labelencoder.fit_transform(Y_cancer)
from sklearn.feature_selection import SelectPercentile 
selector = SelectPercentile(percentile=50)
selector.fit(X_cancer,Y_cancer)
X_cancer = selector.transform(X_cancer)

from sklearn.model_selection import train_test_split
X_cancer_train,X_cancer_test,y_cancer_train,y_cancer_test = train_test_split( X_cancer, Y_cancer, test_size=0.2,random_state=0)


## SVM Classifier 

In [ ]:
from sklearn.svm import SVC

#Linear Classifier
cancer_linear_classifier = SVC(C=1.0,kernel='linear')
cancer_linear_classifier.fit(X_cancer_train,y_cancer_train)
Y_cancer_linear_pred = cancer_linear_classifier.predict(X_cancer_test)
from sklearn.metrics import confusion_matrix, accuracy_score
cancer_linear_cm = confusion_matrix(y_cancer_test,Y_cancer_linear_pred)
print("cm of linear svm is \n ", cancer_linear_cm)

circles_linear_ac = (accuracy_score(y_cancer_test,Y_cancer_linear_pred)*100)
print("accuracy of linear svm is \n ", circles_linear_ac)

cm of linear svm is 
  [[7 0 0 0]
 [0 8 0 0]
 [0 0 9 0]
 [0 0 5 3]]
accuracy of linear svm is 
  84.375


In [ ]:
from sklearn.model_selection import cross_val_score
cancer_svm_accuracies = cross_val_score( estimator = cancer_linear_classifier, X =X_cancer_train, y=y_cancer_train, cv=10)
print("Accuracy for Circles_Dataset using linear SVM: {:.2f} %".format(cancer_svm_accuracies.mean()*100))

Accuracy for Circles_Dataset using linear SVM: 81.22 %


In [ ]:
import sklearn.metrics
import math
def matrix_metrix(y_cancer_test,Y_cancer_linear_pred,beta):
   CM = confusion_matrix(y_cancer_test,Y_cancer_linear_pred)
   TN = CM[0][0]
   FN = CM[1][0] 
   TP = CM[1][1]
   FP = CM[0][1]
   Population = TN+FN+TP+FP
   Prevalence = round( (TP+FP) / Population*100)
   Sensitivity= round(TP/(TP+FN)*100)
   Specificity= round(TN/(TN+FP)*100)
   Accuracy   = round( ((TP+TN)/ Population)*100,4)
   PPV  = round(( TP / (TP+FP))*100,2)
   NPV        = round( TN / (TN+FN)*100,2)  
   mat_met = pd.DataFrame({
'Metric':['TP','TN','FP','FN','Prevalence','Sensitivity','Specificity','Accuracy','PPV','NPV'],     'Value':[TP,TN,FP,FN,Prevalence,Sensitivity,Specificity,Accuracy,PPV,NPV]})
   return (mat_met)

In [ ]:
beta = 0.4
mat_met = matrix_metrix(y_cancer_test,Y_cancer_linear_pred,beta)
#convert float into integer
def round_int(x):
    if x in [float("-inf"),float("inf")]: return float("nan")
    return int(round(x))
print (mat_met)

        Metric  Value
0           TP    8.0
1           TN    7.0
2           FP    0.0
3           FN    0.0
4   Prevalence   53.0
5  Sensitivity  100.0
6  Specificity  100.0
7     Accuracy  100.0
8          PPV  100.0
9          NPV  100.0


##  Random forest Classification Method

In [ ]:
from sklearn.ensemble import RandomForestClassifier
cancer_RF_classifier = RandomForestClassifier( random_state=0, criterion = 'entropy', n_estimators = 150)
cancer_RF_classifier.fit(X_cancer_train,y_cancer_train)
Y_cancer_RF_pred = cancer_RF_classifier.predict(X_cancer_test)

from sklearn.metrics import confusion_matrix, accuracy_score
cancer_RF_cm = confusion_matrix(y_cancer_test,Y_cancer_RF_pred)
print("cm of Random Forest is \n ", cancer_RF_cm)

circles_RF_ac = (accuracy_score(y_cancer_test,Y_cancer_RF_pred)*100)
print("accuracy of Random Forest  is \n ", circles_RF_ac)

cm of Random Forest is 
  [[7 0 0 0]
 [0 8 0 0]
 [0 0 9 0]
 [0 0 5 3]]
accuracy of Random Forest  is 
  84.375


In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
# cv = KFold(n_splits=10, random_state=1, shuffle=True)
# scores = cross_val_score(cancer_RF_classifier, X_cancer_test, y_cancer_test, scoring='accuracy', cv=cv, n_jobs=-1)
# print(scores.mean()*100)
cancer_svm_accuracies = cross_val_score( estimator = cancer_RF_classifier, X =X_cancer_train, y=y_cancer_train, cv=10)
print("Accuracy for Circles_Dataset using linear randomforest: {:.2f} %".format(cancer_svm_accuracies.mean()*100))

Accuracy for Circles_Dataset using linear randomforest: 85.00 %


In [ ]:
import sklearn.metrics
import math
def matrix_metrix(y_cancer_test,Y_cancer_RF_pred,beta):
   CM = confusion_matrix(y_cancer_test,Y_cancer_RF_pred)
   TN = CM[0][0]
   FN = CM[1][0] 
   TP = CM[1][1]
   FP = CM[0][1]
   Population = TN+FN+TP+FP
   Prevalence = round( (TP+FP) / Population*100)
   Sensitivity= round(TP/(TP+FN)*100)
   Specificity= round(TN/(TN+FP)*100)
   Accuracy   = round( (TP+TN)/ Population*100,4)
   PPV  = round(( TP / (TP+FP))*100,2)
   NPV        = round( TN / (TN+FN)*100,2)  
   mat_met = pd.DataFrame({
'Metric':['TP','TN','FP','FN','Prevalence','Sensitivity','Specificity','Accuracy','PPV','NPV'],     'Value':[TP,TN,FP,FN,Prevalence,Sensitivity,Specificity,Accuracy,PPV,NPV]})
   return (mat_met)

In [ ]:
beta = 0.4
mat_met = matrix_metrix(y_cancer_test,Y_cancer_RF_pred,beta)
#convert float into integer
def round_int(x):
    if x in [float("-inf"),float("inf")]: return float("nan")
    return int(round(x))
print (mat_met)

        Metric  Value
0           TP    8.0
1           TN    7.0
2           FP    0.0
3           FN    0.0
4   Prevalence   53.0
5  Sensitivity  100.0
6  Specificity  100.0
7     Accuracy  100.0
8          PPV  100.0
9          NPV  100.0


Feature Selection combine with NN

In [ ]:
from sklearn.neural_network import MLPClassifier
circles_NN_classifier = MLPClassifier(solver = 'lbfgs', activation = 'logistic')
circles_NN_classifier.fit(X_cancer_train,y_cancer_train)
Y_circles_NN_pred = circles_NN_classifier.predict(X_cancer_test)

from sklearn.metrics import confusion_matrix, accuracy_score
circles_NN_cm = confusion_matrix(y_cancer_test,Y_circles_NN_pred)
print ("Confusion matrix for circles Dataset with MLP classifier is : ")
print(circles_NN_cm)

circles_NN_ac = (accuracy_score(y_cancer_test,Y_circles_NN_pred)*100)
print ("Accuracy for circles Dataset with MLP classifier is :")
print(circles_NN_ac)

Confusion matrix for circles Dataset with MLP classifier is : 
[[7 0 0 0]
 [0 8 0 0]
 [0 0 9 0]
 [0 0 5 3]]
Accuracy for circles Dataset with MLP classifier is :
84.375


Cross Validation on NN


In [ ]:
cancer_NN_accuracies = cross_val_score( estimator = circles_NN_classifier, X =X_cancer_train, y=y_cancer_train, cv=10)
print("Accuracy for Circles_Dataset using NN: {:.2f} %".format(cancer_NN_accuracies.mean()*100))

Accuracy for Circles_Dataset using NN: 65.32 %


In [ ]:
import sklearn.metrics
import math
def matrix_metrix(y_cancer_test,Y_cancer_linear_pred,beta):
   CM = confusion_matrix(y_cancer_test,Y_cancer_linear_pred)
   TN = CM[0][0]
   FN = CM[1][0] 
   TP = CM[1][1]
   FP = CM[0][1]
   Population = TN+FN+TP+FP
   Prevalence = round( (TP+FP) / Population*100)
   Sensitivity= round(TP/(TP+FN)*100)
   Specificity= round(TN/(TN+FP)*100)
   Accuracy   = round( ((TP+TN)/ Population)*100,4)
   PPV  = round(( TP / (TP+FP))*100,2)
   NPV        = round( TN / (TN+FN)*100,2)  
   mat_met = pd.DataFrame({
'Metric':['TP','TN','FP','FN','Prevalence','Sensitivity','Specificity','Accuracy','PPV','NPV'],     'Value':[TP,TN,FP,FN,Prevalence,Sensitivity,Specificity,Accuracy,PPV,NPV]})
   return (mat_met)

## Neural Networks 

In [ ]:
import tensorflow as tf
from tensorflow import keras
model_2 = tf.keras.models.Sequential()
#Input and hidden sigmoid
model_2.add(tf.keras.layers.Dense(units = 6, activation = 'sigmoid'))
#2nd Hidden layer
model_2.add(tf.keras.layers.Dense(units = 7, activation = 'sigmoid'))
#output layer
model_2.add(tf.keras.layers.Dense(units = 5, activation = 'relu'))
#compiling the NN
model_2.compile ( optimizer='sgd', metrics= ['accuracy'] ,loss= 'binary_crossentropy' )
# fitting the model with batch learning
data=model_2.fit(X_cancer_train,y_cancer_train, batch_size = 32, epochs = 50,validation_data=(X_cancer, Y_cancer) )

Epoch 1/50
4/4 [==============================] - 1s 67ms/step - loss: 9.3685 - accuracy: 0.1111 - val_loss: 8.6788 - val_accuracy: 0.1392
Epoch 2/50
4/4 [==============================] - 0s 15ms/step - loss: 8.4643 - accuracy: 0.1111 - val_loss: 8.3654 - val_accuracy: 0.1392
Epoch 3/50
4/4 [==============================] - 0s 15ms/step - loss: 8.4926 - accuracy: 0.1111 - val_loss: 8.1743 - val_accuracy: 0.1392
Epoch 4/50
4/4 [==============================] - 0s 15ms/step - loss: 7.9907 - accuracy: 0.1111 - val_loss: 5.9252 - val_accuracy: 0.1392
Epoch 5/50
4/4 [==============================] - 0s 18ms/step - loss: 4.9951 - accuracy: 0.1111 - val_loss: 4.0013 - val_accuracy: 0.1392
Epoch 6/50
4/4 [==============================] - 0s 19ms/step - loss: 3.8762 - accuracy: 0.1111 - val_loss: 4.0013 - val_accuracy: 0.1392
Epoch 7/50
4/4 [==============================] - 0s 15ms/step - loss: 3.8762 - accuracy: 0.1111 - val_loss: 4.0013 - val_accuracy: 0.1392
Epoch 8/50
4/4 [===========